### ISSUE TITLE
[IDEA] Set up guide page as a home directory

### ISSUE THREAD

**Issue by ux-git** [sws2apps/sws2apps-docs#248]
**Describe the idea**

Is it possible to skip the home page (quite dummy one in our case) at guide.organized-app.com and go straight to the guide itself (currently at https://guide.organized-app.com/docs/category/app-overview)?

We already have a well-explaining page about.organized-app.com. So once user wants to read a guide it would make a lot of sense to redirect them directly to [this](https://guide.organized-app.com/docs/category/app-overview) page instead of showing one more "Home page" on Docusaurus. Removing this page completely (or at least fully hiding without an ability to open it even by clicking on the logo in the header) will make it harder to get lost or confused.

I just think that in our case it's an unnecessary extra step, since we already have a landing page.

**Comment by rhahao** [comment]
I will check this.
