### ISSUE TITLE
[FEAT] Add search field

### ISSUE THREAD

**Issue by ux-git** [sws2apps/sws2apps-docs#337]
@rhahao could you please add a [search field](https://docusaurus.io/docs/search) to the top navigation bar? The information base becomes bigger and bigger and even I get lost sometimes.

**Comment by rhahao** [comment]
Noted. I will prepare a PR for that very soon.

**Comment by ux-git** [comment]
Thanks!

**Comment by rhahao** [comment]
Request to apply for [Algolia DocSearch](https://docusaurus.io/docs/search#using-algolia-docsearch) sent. Waiting for their approval...
