### ISSUE TITLE
[FIX] Search bar improvement

### ISSUE THREAD

**Issue by ux-git** [sws2apps/sws2apps-docs#444]
On desktop, please move the search bar to the middle-like position, and make it way longer to be more noticeable and easier to use.

**Screenshots**

<img width="1659" alt="Bildschirmfoto 2024-11-27 um 09 22 41" src="https://github.com/user-attachments/assets/2850ba12-ad2a-465c-9c12-cc30ced95067">

**Comment by mrtavor** [comment]
Done 👍

**Comment by ux-git** [comment]
Awesome, thanks @mrtavor
