### ISSUE TITLE
[FEAT] Custom emojis for documentation

### ISSUE THREAD

**Issue by ux-git** [sws2apps/sws2apps-docs#448]
Customize the emojis for each article while viewing the parent category instead of the current same emojis. Here's how to do this:
https://github.com/facebook/docusaurus/discussions/10476

<img width="1017" alt="Screenshot 2024-12-06 at 15 14 41" src="https://github.com/user-attachments/assets/6adc4bb4-c566-460f-8d4d-310acce203f5">

**Comment by mrtavor** [comment]
Now it's done and looks awesome 👍

**Comment by ux-git** [comment]
Than you s lot!
